logging:
  level:
    blog: WARN
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor: ERROR
      nodeValue: WARN
      springframework:
        security: ERROR
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:postgres://root:MKktOBYWEvGcMgk4wqowAiFaDqdTG3Da@dpg-cjdqkp0q339s73em7jug-a/home_manager_3k02
    username: root
    password: ${db_password}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    protocol: smtp
    jndi-name: mail/Session
    username: bg.home.manager@gmail.com
    password: ${mail_password}
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          mime:
            charset: true
  mvc:
    hidden-method:
      filter:
        enabled: true
  thymeleaf:
    cache: false
    enabled: true
    servlet:
      produce-partial-output-while-processing: false
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/